-- Reseed all identity sequences in the "dbo" schema to MAX(id) of each table.
--
-- Why: the SQL Server -> PostgreSQL move (migration 20260521075454_MoveToPostgresql)
-- bulk-copied rows with their original Ids. Because the identity columns are
-- GENERATED BY DEFAULT AS IDENTITY, explicit-Id inserts do NOT advance the backing
-- sequence, so it still hands out low, already-used values -> 23505 duplicate key
-- (e.g. PK_Hikes). This resets every identity sequence to the current MAX(id) so the
-- next insert uses MAX(id)+1.
--
-- Safe to run repeatedly. Run once against production (ideally on a restored copy first).
--   psql "<connection string>" -f reseed-identity-sequences.sql

DO $$
DECLARE
    r          RECORD;
    seq        TEXT;
    max_id     BIGINT;
BEGIN
    FOR r IN
        SELECT c.table_schema, c.table_name, c.column_name
        FROM   information_schema.columns c
        WHERE  c.table_schema = 'dbo'
        AND    c.is_identity   = 'YES'
    LOOP
        seq := pg_get_serial_sequence(
                   format('%I.%I', r.table_schema, r.table_name),
                   r.column_name);

        IF seq IS NULL THEN
            CONTINUE;  -- column has no backing sequence, skip
        END IF;

        EXECUTE format('SELECT MAX(%I) FROM %I.%I',
                       r.column_name, r.table_schema, r.table_name)
        INTO max_id;

        -- 3-arg setval with is_called: next nextval() returns max_id + 1.
        -- If the table is empty (max_id IS NULL) leave the sequence untouched.
        IF max_id IS NOT NULL THEN
            PERFORM setval(seq, max_id, true);
            RAISE NOTICE 'Reseeded %.% (%): next id = %',
                r.table_schema, r.table_name, r.column_name, max_id + 1;
        ELSE
            RAISE NOTICE 'Skipped %.% (%): table is empty',
                r.table_schema, r.table_name, r.column_name;
        END IF;
    END LOOP;
END $$;
