// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(StigViddDbContext))]
    partial class StigViddDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Data.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Grade")
                        .HasColumnType("real");

                    b.Property<int>("TrailId")
                        .HasColumnType("int");

                    b.Property<string>("TrailReview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrailId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grade = 5f,
                            TrailId = 1,
                            TrailReview = "Tiveden är verkligen utmanande! Branta klippor och fantastisk natur. Mina ben känner fortfarande av det!",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Grade = 4f,
                            TrailId = 2,
                            TrailReview = "Storsjöleden var tuffare än förväntat men så vacker! Perfekt träning.",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Grade = 5f,
                            TrailId = 3,
                            TrailReview = "Tångaleden är en favorit! Spångarna gör det enklare och utsikten är magisk.",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Grade = 4f,
                            TrailId = 4,
                            TrailReview = "Vildmarksleden Årås är mysig! Såg både kor och får längs vägen. Barnvänlig.",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Grade = 4f,
                            TrailId = 1,
                            TrailReview = "Tiveden är inget för nybörjare. Ta med vatten och ta det lugnt!",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Grade = 5f,
                            TrailId = 1,
                            TrailReview = "Bästa leden i området! Tiveden är krävande men så otroligt vacker med alla klippformationer.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            Grade = 5f,
                            TrailId = 2,
                            TrailReview = "Storsjöleden passerar vackra vyer över sjön. Värt ansträngningen!",
                            UserId = 5
                        },
                        new
                        {
                            Id = 8,
                            Grade = 4f,
                            TrailId = 2,
                            TrailReview = "Lite hala stenar på vissa ställen i Storsjöleden, men annars toppen!",
                            UserId = 6
                        },
                        new
                        {
                            Id = 9,
                            Grade = 4f,
                            TrailId = 3,
                            TrailReview = "Tångaleden är perfekt för en avslappnad vandring. Spångarna är välbyggda.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            Grade = 5f,
                            TrailId = 3,
                            TrailReview = "Gick Tångaleden i solnedgången - magiskt! Rekommenderas starkt.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            Grade = 5f,
                            TrailId = 4,
                            TrailReview = "Årås är superbra för hela familjen! Kan till och med cykla delar av sträckan.",
                            UserId = 5
                        },
                        new
                        {
                            Id = 12,
                            Grade = 4f,
                            TrailId = 4,
                            TrailReview = "Fin blandning av natur och lantbrukslandskap på Vildmarksleden. Väldigt trivsamt!",
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            Grade = 4f,
                            TrailId = 1,
                            TrailReview = "Tiveden utmanade verkligen min kondition. Ta med snacks och vatten!",
                            UserId = 6
                        },
                        new
                        {
                            Id = 14,
                            Grade = 4f,
                            TrailId = 2,
                            TrailReview = "Storsjöleden hade vackra höstfärger när vi gick den. Lite lerig efter regn.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 15,
                            Grade = 5f,
                            TrailId = 3,
                            TrailReview = "Tångaleden är min go-to för en snabb eftermiddagspromenad. Lugnt och skönt!",
                            UserId = 6
                        },
                        new
                        {
                            Id = 16,
                            Grade = 5f,
                            TrailId = 4,
                            TrailReview = "Årås är en underbar led! Grusvägen gör det enkelt och naturen är vacker.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 17,
                            Grade = 4f,
                            TrailId = 1,
                            TrailReview = "Tiveden kräver bra skor med bra grepp. Klipporna kan vara hala!",
                            UserId = 5
                        },
                        new
                        {
                            Id = 18,
                            Grade = 3f,
                            TrailId = 2,
                            TrailReview = "Lite för tuff för mig personligen men vacker natur i Storsjöleden.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            Grade = 3f,
                            TrailId = 5,
                            TrailReview = "Gesebol är perfekt för en lugn promenad! Bara asfalt och grusväg men fin natur.",
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            Grade = 3f,
                            TrailId = 5,
                            TrailReview = "Enkel och trevlig led, passar bra för joggingrundan också, mycket platt underlag!",
                            UserId = 2
                        },
                        new
                        {
                            Id = 21,
                            Grade = 2f,
                            TrailId = 5,
                            TrailReview = "Kort och halvmysig tur. Barnen tyckte det var tråkigt med så mkt asfalt.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 22,
                            Grade = 5f,
                            TrailId = 5,
                            TrailReview = "Gesebol är en favorit för kvällspromenader. Lugnt och fridfullt!",
                            UserId = 6
                        },
                        new
                        {
                            Id = 23,
                            Grade = 4f,
                            TrailId = 6,
                            TrailReview = "Hultafors har lite mer utmaning än man tror! Fina stigar genom skogen.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 24,
                            Grade = 4f,
                            TrailId = 6,
                            TrailReview = "Bra träningsrunda! Lite variation i terrängen gör det intressant.",
                            UserId = 5
                        },
                        new
                        {
                            Id = 25,
                            Grade = 5f,
                            TrailId = 6,
                            TrailReview = "Hultafors överraskade positivt. Vacker skogsmark och bra skyltning.",
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            Grade = 3f,
                            TrailId = 6,
                            TrailReview = "Lite för korta stigdelar för min smak men annars trevlig led.",
                            UserId = 3
                        },
                        new
                        {
                            Id = 27,
                            Grade = 5f,
                            TrailId = 7,
                            TrailReview = "Nässehult är absolut bäst för barnvagn! Släta vägar hela vägen.",
                            UserId = 2
                        },
                        new
                        {
                            Id = 28,
                            Grade = 5f,
                            TrailId = 7,
                            TrailReview = "Perfekt tillgänglig led. Kunde köra rullstol utan problem!",
                            UserId = 6
                        },
                        new
                        {
                            Id = 29,
                            Grade = 4f,
                            TrailId = 7,
                            TrailReview = "Enkelt och lättgått. Bra för äldre eller de som behöver tillgänglighet.",
                            UserId = 4
                        },
                        new
                        {
                            Id = 30,
                            Grade = 4f,
                            TrailId = 7,
                            TrailReview = "Nässehult är mysig! Fin promenad längs med bra underlag.",
                            UserId = 5
                        },
                        new
                        {
                            Id = 31,
                            Grade = 3f,
                            TrailId = 5,
                            TrailReview = "Gesebol är på 6 km. Lagom längd men tråkigt med så mkt bilvägar!",
                            UserId = 4
                        },
                        new
                        {
                            Id = 32,
                            Grade = 4f,
                            TrailId = 6,
                            TrailReview = "Hultafors ger lite träning trots att den är kort. Sköna stigar!",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.ReviewImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/mock-review/review0011.jpg",
                            ReviewId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/mock-review/review0012.jpg",
                            ReviewId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/mock-review/review0031.jpg",
                            ReviewId = 3
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Statistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("TotalKilometers")
                        .HasColumnType("float");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.Property<int>("TotalWalkedTrails")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Trail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Accessability")
                        .HasColumnType("bit");

                    b.Property<string>("AccessabilityInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordinatesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TrailLenght")
                        .HasColumnType("float");

                    b.Property<string>("TrailSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailSymbolImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accessability = false,
                            AccessabilityInfo = "Delvis väldigt svår terräng, kräver god fysik",
                            Classification = "Svår",
                            Description = "En dramatisk och utmanande vandring genom djupa skogar, höga klippor och stenformationer.",
                            Name = "Tiveden",
                            TrailLenght = 9.5,
                            TrailSymbol = "Röd markering",
                            TrailSymbolImage = "https://inkaben.se/stigvidd/mock/mock-trail-symbol.png"
                        },
                        new
                        {
                            Id = 2,
                            Accessability = false,
                            AccessabilityInfo = "Delvis väldigt svår terräng, kräver god fysik",
                            Classification = "Svår",
                            Description = "En varierad och bitvis krävande led som slingrar sig runt Storsjöns skogsområden.",
                            Name = "Storsjöleden",
                            TrailLenght = 8.5,
                            TrailSymbol = "Blå markering",
                            TrailSymbolImage = "https://inkaben.se/stigvidd/mock/mock-trail-symbol.png"
                        },
                        new
                        {
                            Id = 3,
                            Accessability = false,
                            AccessabilityInfo = "Stigar, spångar och grusväg, vacker utsikt",
                            Classification = "Medel",
                            Description = "En naturskön rundslinga genom Hofsnäsområdet med blandning av stigar, spångar och öppna utsikter.",
                            Name = "Tångaleden",
                            TrailLenght = 9.0999999999999996,
                            TrailSymbol = "Orange markering",
                            TrailSymbolImage = "https://inkaben.se/stigvidd/mock/mock-trail-symbol.png"
                        },
                        new
                        {
                            Id = 4,
                            Accessability = true,
                            AccessabilityInfo = "Naturstigar, beteshagar, spång och grusväg",
                            Classification = "Medel",
                            Description = "En inbjudande led som tar dig genom beteshagar, skogar och kulturmiljöer kring Årås.",
                            Name = "Vildmarksleden Årås",
                            TrailLenght = 8.5,
                            TrailSymbol = "Grön markering",
                            TrailSymbolImage = "https://inkaben.se/stigvidd/mock/mock-trail-symbol.png"
                        },
                        new
                        {
                            Id = 5,
                            Accessability = false,
                            AccessabilityInfo = "Asfalt, stig och grusväg",
                            Classification = "Lätt",
                            Description = "En lättvandrad slinga som kombinerar skogsstigar, grusväg och kortare asfaltspartier.",
                            Name = "Gesebol",
                            TrailLenght = 6.0,
                            TrailSymbol = "Röd markering med en 6:a på",
                            TrailSymbolImage = "https://inkaben.se/stigvidd/mock/mock-trail-symbol.png"
                        },
                        new
                        {
                            Id = 6,
                            Accessability = false,
                            AccessabilityInfo = "Asfalt, stigar och grusväg",
                            Classification = "Medel",
                            Description = "En medelsvår led med både skogsstigar, grusvägar och öppnare partier.",
                            Name = "Hultafors",
                            TrailLenght = 4.5,
                            TrailSymbol = "Blå markering",
                            TrailSymbolImage = "https://inkaben.se/stigvidd/mock/mock-trail-symbol.png"
                        },
                        new
                        {
                            Id = 7,
                            Accessability = true,
                            AccessabilityInfo = "Asfalt och grusväg",
                            Classification = "Lätt",
                            Description = "En lätt och tillgänglig led på asfalt och grusväg som passar för alla.",
                            Name = "Nässehult",
                            TrailLenght = 4.5,
                            TrailSymbol = "Nässla",
                            TrailSymbolImage = "https://inkaben.se/stigvidd/mock/nassla.png"
                        },
                        new
                        {
                            Id = 8,
                            Accessability = true,
                            AccessabilityInfo = "Asfalt, stig och grusväg",
                            Classification = "Lätt",
                            Description = "En kort och lättvandrad slinga i det vackra området kring Hofsnäs.",
                            Name = "Hoffsnäs",
                            TrailLenght = 4.7999999999999998,
                            TrailSymbol = "Läderbagge",
                            TrailSymbolImage = "https://inkaben.se/stigvidd/mock/mock-trail-symbol.png"
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.TrailImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrailId");

                    b.ToTable("TrailImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/tiveden/20250925122257.jpg",
                            TrailId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/tiveden/20250925122143.jpg",
                            TrailId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/tiveden/20250925110314.jpg",
                            TrailId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/storsjon/20241102113934.jpg",
                            TrailId = 2
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/storsjon/20241102121010.jpg",
                            TrailId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/storsjon/20241102112335.jpg",
                            TrailId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/tangaleden/20250902122917.jpg",
                            TrailId = 3
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/tangaleden/20250902130421.jpg",
                            TrailId = 3
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/hofsnas/20250822093635.jpg",
                            TrailId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/aras/20250818102417.jpg",
                            TrailId = 4
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/aras/20250818094810.jpg",
                            TrailId = 4
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/aras/20250818103640.jpg",
                            TrailId = 4
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/aras/20250818112639.jpg",
                            TrailId = 4
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/gesebol/20250824100243.jpg",
                            TrailId = 5
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/gesebol/20250824105053.jpg",
                            TrailId = 5
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/gesebol/20250824095946.jpg",
                            TrailId = 5
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/gesebol/20250824110936.jpg",
                            TrailId = 5
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/hultafors/20240217105404.jpg",
                            TrailId = 6
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/hultafors/20240217105412.jpg",
                            TrailId = 6
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/hultafors/20240217111003.jpg",
                            TrailId = 6
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/nasslehult/20240119131715.jpg",
                            TrailId = 7
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/nasslehult/20240119132416.jpg",
                            TrailId = 7
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/nasslehult/20240120103723.jpg",
                            TrailId = 7
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/hoffsnas/20240912150635.jpg",
                            TrailId = 8
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/hoffsnas/20250524103240.jpg",
                            TrailId = 8
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/hoffsnas/20250524104329.jpg",
                            TrailId = 8
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/hoffsnas/20250822090107.jpg",
                            TrailId = 8
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/hoffsnas/20250822090109.jpg",
                            TrailId = 8
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/hoffsnas/20250822092315.jpg",
                            TrailId = 8
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "https://inkaben.se/stigvidd/mock/hoffsnas/20250822093635.jpg",
                            TrailId = 8
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.TrailLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrailId");

                    b.ToTable("TrailLinks");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "natur@example.local",
                            NickName = "NaturElskaren"
                        },
                        new
                        {
                            Id = 2,
                            Email = "vandrar@example.local",
                            NickName = "VandrarVennen"
                        },
                        new
                        {
                            Id = 3,
                            Email = "fjall@example.local",
                            NickName = "FjällFanatikern"
                        },
                        new
                        {
                            Id = 4,
                            Email = "skog@example.local",
                            NickName = "SkogsSpringaren"
                        },
                        new
                        {
                            Id = 5,
                            Email = "aventyr@example.local",
                            NickName = "ÄventyrAnna"
                        },
                        new
                        {
                            Id = 6,
                            Email = "vildmark@example.local",
                            NickName = "VildmarksViktor"
                        });
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Review", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.Trail", "Trail")
                        .WithMany()
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.ReviewImage", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Statistics", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.User", "User")
                        .WithOne("MyStatistics")
                        .HasForeignKey("Infrastructure.Data.Entities.Statistics", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.TrailImage", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.Trail", "Trail")
                        .WithMany("TrailImages")
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trail");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.TrailLink", b =>
                {
                    b.HasOne("Infrastructure.Data.Entities.Trail", "Trail")
                        .WithMany("TrailLinks")
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trail");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.Trail", b =>
                {
                    b.Navigation("TrailImages");

                    b.Navigation("TrailLinks");
                });

            modelBuilder.Entity("Infrastructure.Data.Entities.User", b =>
                {
                    b.Navigation("MyStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
